#ifndef __MMETA_IGNORE__

// This file was generated by minimeta. Don't touch it!!
#pragma once
#include "Minimeta.hpp"
struct Vec3;
namespace mmeta{
template <>
struct is_serializable<Vec3> {
  static constexpr bool value = true;
};
}
class Player;
namespace mmeta{
template <>
struct is_serializable<Player> {
  static constexpr bool value = true;
};
}
#endif