#ifndef __MMETA__

// This file was generated by minimeta. Don't touch it!!
#pragma once
#include "Minimeta.hpp"
class CustomAccessors;
namespace mmeta{
  template <>
  struct is_serializable<CustomAccessors> : std::true_type {};

  }
struct MoreCustomAccessors;
namespace mmeta{
  template <>
  struct is_serializable<MoreCustomAccessors> : std::true_type {};

  }
#endif