
// ========================================================================-------
// ======= This file was generated by minimeta. Don't touch it!!!!
// ========================================================================-------
#ifndef __MMETA__
#pragma once
#include <mmeta/minimeta.hpp>


class CustomAccessors;
MMETA_CLASS(CustomAccessors,
	MMETA_FIELD(show),
	MMETA_FIELD(showPrivate),
)

struct MoreCustomAccessors;
MMETA_CLASS(MoreCustomAccessors,
	MMETA_FIELD(Show),
)


#endif
// ========================================================================-------
// ======= This file was generated by minimeta. Don't touch it!!!!
// ========================================================================-------
