
// ========================================================================-------
// ======= This file was generated by minimeta. Don't touch it!!!!
// ========================================================================-------
#ifndef __MMETA__
#pragma once
#include <mmeta/minimeta.hpp>


struct Vec3;
MMETA_CLASS(Vec3,
	MMETA_FIELD(X),
	MMETA_FIELD(Y),
	MMETA_FIELD(Z),
)


#endif
// ========================================================================-------
// ======= This file was generated by minimeta. Don't touch it!!!!
// ========================================================================-------
