
// ========================================================================-------
// ======= This file was generated by minimeta. Don't touch it!!!!
// ========================================================================-------
#ifndef __MMETA__
#pragma once
#include <mmeta/minimeta.hpp>


struct Vec3;
MMETA_CLASS(Vec3,
	MMETA_FIELD(X),
	MMETA_FIELD(Y),
	MMETA_FIELD(Z),
)

struct ColorRGB;
MMETA_CLASS(ColorRGB,
	MMETA_FIELD(R),
	MMETA_FIELD(G),
	MMETA_FIELD(B),
)

class Player;
MMETA_CLASS(Player,
	MMETA_FIELD(m_id),
	MMETA_FIELD(m_state),
	MMETA_FIELD(m_integers),
	MMETA_FIELD(m_nested),
	MMETA_FIELD(m_targets),
	MMETA_FIELD(m_position),
	MMETA_FIELD(m_name),
)

struct Transform;
MMETA_CLASS(Transform,
	MMETA_FIELD(Position),
	MMETA_FIELD(Rotation),
)


#endif
// ========================================================================-------
// ======= This file was generated by minimeta. Don't touch it!!!!
// ========================================================================-------
